- name: Disable and enable redis 7
  ansible.builtin.shell: dnf module disable redis -y; dnf module enable redis:7 -y

- name: Install Redis
  ansible.builtin.dnf:
    name: redis
    state: latest

- name: Update redis listen address
  ansible.builtin.replace:
    path: /etc/redis.conf
    regexp: '127.0.01'
    replace: '0.0.0.0'

- name: Update redis config protected mode
  ansible.builtin.replace:
    path: /etc/redis/redis.conf
    regexp: 'protected-mode yes'
    replace: 'protected-mode no'

- name: Enable & Start redis service
  ansible.builtin.systemd_service:
    name: redis
    state: started
    enabled: true