- name: Install Python
  ansible.builtin.include_role:
    name: common
    tasks_from: python

- name: Perform systemd setup
  ansible.builtin.include_role:
    name: common
    tasks_from: systemd_setup