- name: Install nodejs
  ansible.builtin.include_role:
    name: common
    tasks_from: docker
- name: Docker container
  community.docker.docker_container:
    name: user
    image: public.ecr.aws/w8x4g9h7/roboshop-v3/user
    ports:
      - "8080:8080"
    env:
      MONGO_URL="{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-{{ env }}/data/{{ app_name }}:MONGO_URL token={{ token }} url=http://vault-int.nareshdevops1218.online:8200') }}"
      REDIS_URL="{{ lookup('community.hashi_vault.hashi_vault', 'secret=roboshop-{{ env }}/data/{{ app_name }}:REDIS_URL token={{ token }} url=http://vault-int.nareshdevops1218.online:8200') }}"
      MONGO="true"
      