- name: Copy rabbitmq db repo file
  ansible.builtin.copy:
    src: rabbitmq.repo
    dest: /etc/yum.repos.d/rabbitmq.repo

- name: Install rabbitmq
  ansible.builtin.dnf:
    name: rabbitmq-server
    state: latest

- name: Enable and start rabbitmq server
  ansible.builtin.systemd_service:
    name: rabbitmq-server
    state: started
    enabled: true

- name: Add rabbitmq user and provide permissions
  community.rabbitmq.rabbitmq_user:
    user: roboshop
    password: roboshop123
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present