- name: Install mysql server
  ansible.builtin.dnf:
    name: mysql-server
    state: latest

- name: Enable & Start mysql service
  ansible.builtin.systemd_service:
    name: mysqld
    state: started
    enabled: true

- name: Setip mysql root password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass RoboShop@1