- name: Install Golang
  ansible.builtin.include_role:
    name: common
    tasks_from: golang

- name: Perform systemd setup
  ansible.builtin.include_role:
    name: common
    tasks_from: systemd_setup