
- name: Install nodejs
  ansible.builtin.include_role:
    name: common
    tasks_from: nodejs
    
- name: Install mongodb client
  ansible.builtin.dnf:
    name: mongodb-mongosh
    state: latest

- name: Load master data
  ansible.builtin.shell: mongosh --host mongodb-dev.nareshdevops1218.online </app/db/master-data.js

- name: Perform systemd setup
  ansible.builtin.include_role:
    name: common
    tasks_from: systemd_setup