- name: Disable and enable nodejs version
  ansible.builtin.shell: dnf module disable nodejs -y; dnf module enable nodejs:20 -y

- name: Install nodejs
  ansible.builtin.dnf:
    name: nodejs
    state: present

- name: Invoke app preset role
  ansible.builtin.include_tasks:
    file: pre_app_setup.yml 

- name: Perform npm Install
  ansible.builtin.shell: npm install
  args:
    chdir: /app