- name: Copy component service file
  ansible.builtin.copy:
    src: "{{app_name}}.service"
    dest: /etc/systemd/system/{{ app_name }}.service

- name: Enable and start the app service
  ansible.builtin.systemd_service:
    state: restarted
    name: {{ app_name }}
    enabled: true
    demon_reload: true