- name: Install nodejs
  ansible.builtin.include_role:
    name: common
    tasks_from: nodejs

- name: Perform systemd setup
  ansible.builtin.include_role:
    name: common
    tasks_from: systemd_setup